## YAML Template.
version: "3.5"

services:
    php:
        container_name: php
        build:
            context: php
        ports:
        - 127.0.0.1:80:80
        volumes:
        - ./app/:/var/www/html
        
    mysql:
        container_name: MySQL
        image: mysql:5.7
        ports:
        - 3306:3306
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: 111111
          MYSQL_DATABASE: testDB
          MYSQL_USER: user
          MYSQL_PASSWORD: user
        volumes:
        - ./databases/mysql:/var/lib/mysql
        networks:
        - default
      
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        ports:
        - 127.0.0.1:8080:80
        environment:
          PMA_HOST: mysql
          PMA_USER: user
          PMA_PASSWORD: user
